import cplex
from cplex.exceptions import CplexError
import sys

print('testing')